apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-dex-ind
    app.kubernetes.io/component: spring-dex-ind
    app.kubernetes.io/instance: spring-dex-ind
  name: spring-dex-ind
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: spring-dex-ind
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: spring-dex-ind
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/test/spring-boot@sha256:e483d8418391e7506bf331608b4feef9ea0a214d09e602862e5e5becde547fb5
        imagePullPolicy: IfNotPresent
        name: spring-dex-ind
        env:
        - name: JAVA_OPTS_APPEND
          value: "-Djavax.net.ssl.trustStore=/cert/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit"
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: properties
          mountPath: /deployments/config
          readOnly: true
        - name: wildcard
          mountPath: /cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: properties
        configMap:
          name: app-properties
      - name: wildcard
        secret:
          secretName: stores
